[package]
name = "elon_sort"
version = "0.1.1"
edition = "2021"
authors = ["williammmm me@williammmm.dev"]
description = "the worst sorting algorithm"
repository = "https://github.com/williamwith4ms/elon_sort"
license = "GPL-3.0"
readme = "README.md"

[dependencies]
rand = "0.9"